modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/North-West-Wind/MoreBoots/issues"

[[mods]]
modId="moreboots"
version="4.0.0"
displayName="More Boots"
updateJSONURL="https://github.com/North-West-Wind/MoreBoots/raw/main/update.json"
displayURL="https://github.com/North-West-Wind/MoreBoots"
logoFile="moreboots.png"
credits="Thanks for playing with More Boots!"
authors="NorthWestWind, Zinaida"
description='''
Oh, you love shoes? Name every boots in this mod.
(Note: There isn't a lot of boots in this mod currently, but it will receive constant updates in the future.)

Major Updates:
Heroic Update - Fully suggested by Zinaida
'''

[[dependencies.moreboots]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moreboots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
